Rails 6.x support
bookmate/active_record_slave pull request #3
Opened 2021-10-06 18:25 UTC by mainameiz

NOTE: database.yml file format was changed.
Now it requires `slave` key to be used instead of `replica` because
Rails 6.1 has new feature for working with multiple databases
and uses `replica` key on its own.

2021-10-07 11:11 UTC, d3mash requested changes

2021-10-07 11:11 UTC, d3mash commented on .github/workflows/.tests.yml
> +          - gemfile: 'rails_6.0'
https://github.com/bookmate/active_record_slave/pull/2#discussion_r724079674 это неактуально)

2021-10-07 11:11 UTC, d3mash approved these changes

2021-10-07 11:37 UTC, merged

2021-10-08 12:35 UTC, irastyapin-bm commented on .github/workflows/.tests.yml
> +          - gemfile: 'rails_6.0'
В `publisher`'е **ещё далеко не** 6.0 🙁 
https://github.com/bookmate/publisher/blob/f39d1f614f8f70965d06c50bc38ffec7b8279573/Gemfile#L9

2021-10-08 12:50 UTC, mainameiz commented on .github/workflows/.tests.yml
> +          - gemfile: 'rails_6.0'
👍